version: '3.8'

services:
  postgres:
    build:
      dockerfile: ./postgres-init/Dockerfile
    container_name: postgres_app_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: postgres-pinger:1.0 
    container_name: postgres_pinger
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app/logs:/app/logs
    restart: unless-stopped